web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  dockerfile: ./bin/docker/php5-4/Dockerfile
  ports:
      - "80:80"
  env_file:
    - ./bin/conf/stage/env_stage
mysql:
  image: mysql:5.6.23
  env_file:
     - ./bin/conf/stage/env_stage
