web:
  container_name: jira-mg-latest.hipay-pos-platform.com
  build: .
  dockerfile: ./bin/docker/php5-6/Dockerfile
  ports:
      - "80:80"
  environment:
    - SAMPLE_DATA_VERSION={SAMPLE_DATA_VERSION}
    - MAGENTO_VERSION={MAGENTO_VERSION}
  env_file:
    - ./bin/conf/stage/hipay.env.sample
    - ./bin/conf/stage/mage.env.sample
    - ./bin/conf/stage/mysql.env.sample
  volumes:
    - ./log:/var/www/htdocs/var/log
mysql:
  image: mysql:5.6.23
  env_file:
     - ./bin/conf/stage/mysql.env.sample
smtp:
  container_name: smtp-mg-latest.hipay-pos-platform.com
  ports:
     - "1095:80"
  image: hipay/mailcatcher:1.0.0
