web:
  container_name: {CONTAINER_NAME_WEB}
  build: .
  dockerfile: ./bin/docker/php5-6/Dockerfile
  ports:
      - "{PORT_WEB}:80"
  environment:
    - SAMPLE_DATA_VERSION=1.9
    - MAGENTO_VERSION=1.9.2.3
  env_file:
    - ./bin/conf/production/hipay.env
    - ./bin/conf/production/mage.env.sample
    - ./bin/conf/production/mysql.env.sample
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
mysql:
  container_name: {CONTAINER_NAME_MYSQL}
  image: mysql:5.6.23
  ports:
    - "{PORT_MYSQL}:3306"
  env_file:
     - ./bin/conf/production/mysql.env.sample
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
smtp:
  container_name: {CONTAINER_NAME_SMTP}
  ports:
     - "{PORT_SMTP}:80"
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
