version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6.30-apache
  test:
    docker:
      - image: circleci/php:5.6.30-apache
    steps:
      - checkout
      - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      - sudo tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
      - sudo mv phantomjs-2.1.1-linux-x86_64 /home/ubuntu/bin/
      - sudo chmod a+x /home/ubuntu/bin/phantomjs-2.1.1-linux-x86_64
      - sudo ln -s --force /home/ubuntu/bin/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
      - npm install -g casperjs@1.1.3
      - npm install -g junit-viewer
      - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/conf/stage/hipay.env.sample
      - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/conf/stage/hipay.env.sample
      - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/conf/stage/hipay.env.sample
      - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/conf/stage/hipay.env.sample
      - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/conf/stage/hipay.env.sample
      - sed -i -e "s/{LOGIN_BACKEND\}/$LOGIN_BACKEND/" ./bin/conf/stage/test.env.sample
      - sed -i -e "s/{PASS_BACKEND\}/$PASS_BACKEND/" ./bin/conf/stage/test.env.sample
      - sed -i -e "s/{LOGIN_PAYPAL\}/$LOGIN_PAYPAL/" ./bin/conf/stage/test.env.sample
      - sed -i -e "s/{PASS_PAYPAL\}/$PASS_PAYPAL/" ./bin/conf/stage/test.env.sample
      - mkdir $CIRCLE_ARTIFACTS/casper_report
      - mkdir $CIRCLE_ARTIFACTS/screenshots
      - sh bin/docker/generate_dockerfile.sh
      - docker-compose -f docker-compose.yml -f docker-compose.stage.yml build --no-cache
      - docker-compose -f docker-compose.yml -f docker-compose.stage.yml up -d
      - sleep 60
      - curl --retry 30 --retry-delay 3 -v $MAGENTO_URL:$PORT_WEB
      - curl --retry 30 --retry-delay 3 -v $URL_MAILCATCHER
      - sh bin/tests/casper_run_circle.sh
      - junit-viewer --results=bin/tests/result.xml --save=bin/tests/report-php5-6.html --minify=false --contracted
      - if [ -d bin/tests/errors/ ]; then mkdir $CIRCLE_ARTIFACTS/screenshots/php5-6; cp bin/tests/errors/* $CIRCLE_ARTIFACTS/screenshots/php5-6; rm -rf bin/tests/errors/; fi
      # - docker-compose stop
      # - docker-compose rm -fv
      # - docker-compose -f docker-compose.yml -f docker-compose.stage-php5-4.yml build --no-cache
      # - docker-compose -f docker-compose.yml -f docker-compose.stage-php5-4.yml up -d
      # - sleep 60
      # - curl --retry 30 --retry-delay 3 -v $MAGENTO_URL:$PORT_WEB
      # - sh bin/tests/casper_run_circle.sh
      # - junit-viewer --results=bin/tests/result.xml --save=bin/tests/report-php5-4.html --minify=false --contracted
      # - if [ -d bin/tests/errors/ ]; then mkdir $CIRCLE_ARTIFACTS/screenshots/php5-4; cp bin/tests/errors/* $CIRCLE_ARTIFACTS/screenshots/php5-4; rm -rf bin/tests/errors/; fi
      - docker-compose stop
      - docker-compose rm -fv
      - docker-compose -f docker-compose.yml -f docker-compose.stage-php7-0.yml build --no-cache
      - docker-compose -f docker-compose.yml -f docker-compose.stage-php7-0.yml up -d
      - sleep 60
      - curl --retry 30 --retry-delay 3 -v $MAGENTO_URL:$PORT_WEB
      - sh bin/tests/casper_run_circle.sh
      - junit-viewer --results=bin/tests/result.xml --save=bin/tests/report-php7-0.html --minify=false --contracted
      - if [ -d bin/tests/errors/ ]; then mkdir $CIRCLE_ARTIFACTS/screenshots/php7-0; cp bin/tests/errors/* $CIRCLE_ARTIFACTS/screenshots/php7-0; fi
      - cp bin/tests/report-php5-6.html $CIRCLE_ARTIFACTS/casper_report/
      # - cp bin/tests/report-php5-4.html $CIRCLE_ARTIFACTS/casper_report/
      - cp bin/tests/report-php7-0.html $CIRCLE_ARTIFACTS/casper_report/
      - deploy:
          feature:
            branch: /feature*/
            commands:
              - sh ./bin/deployment/deploy_staging.sh
